### ISSUE TITLE
Docs not working?

### ISSUE THREAD

**Issue by advaith1** [discordjs/collection#16]
https://discord.js.org/#/docs/main/master/class/Collection says it extends BaseCollection at https://discord.js.org/#/docs/collection, but that URL doesn't work and just redirects to https://discord.js.org/#/docs/main/stable/general/welcome. The only options in the dropdown are Main library, Commando, and RPC; collection is probably supposed to show there.

**Comment by tipakA** [comment]
https://github.com/discordjs/website/issues/41#issuecomment-545393322
Had the issue as well, this helped for me.

**Comment by Monbrey** [comment]
Collection should be showing if you're on the master branch - you'll probably need to clear all cache for the site to get the link and the dropdown to work correctly. I had the same issue a couple weeks back.

**Comment by advaith1** [comment]
Clearing site data in the Application tab worked, thanks!
