### ISSUE TITLE
Not found in NPM

### ISSUE THREAD

**Issue by arnav7633** [discordjs/collection#25]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@discordjs%2fcollection - Not found
npm ERR! 404
npm ERR! 404  '@discordjs/collection@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by almostSouji** [comment]
NPM is having issues https://status.npmjs.org/
