### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by gamer167** [discordjs/collection#28]
I run the cmd npm start and it has this:
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\QCSie\AppData\Roaming\npm-cache\_logs\2020-10-12T14_37_22_148Z-debug.log

**Comment by almostSouji** [comment]
I'm not too sure how you got the idea this package would have a "start" script to begin with. As you can see in [package.json](https://github.com/discordjs/collection/blob/master/package.json) it clearly does not and really shouldn't either.

This is a utility package which exports a data structure no stand-alone project to run.
