### ISSUE TITLE
<collection>#hasAny() Not returning valid results

### ISSUE THREAD

**Issue by OneAndonlyFinbar** [discordjs/collection#54]
### Issue description

Im making a permission handler for my bot and I have this following code in a module:

permissionHandler.js
```js
module.exports = {
    async getStaffPermissionFlags(guild, member){
        if(!member || !guild) return;
        const adminRoles = ['600912549570936833'];
        const moderatorRoles = ['659905403458682937'];

        return{
            admin: member.roles.cache.hasAny(adminRoles),
            moderator: member.roles.cache.hasAny(moderatorRoles)
        }
    },
    execute(client){
        client.permissionsHandler = {}
        client.permissionsHandler.getStaffPermissionFlags = this.getStaffPermissionFlags;
    }
}
```

When the bot is started it runs this file and sets the `permissionHandler.getStaffPermissionFlags` object to a function in the module.

I can then later call this by using
```js
await interaction.client.permissionsHandler.getStaffPermissionFlags(interaction.guild, interaction.member.id);
```

The code is intended to return an object with `admin` and `moderator` boolean values but it always returns false for both values even though my test account has both roles with id's `600912549570936833` for admin and `659905403458682937` for moderator.

Am I using it incorrectly or is it a bug within the `@discordjs/collection` package function?

It appears in [the documentation](https://discord.js.org/#/docs/collection/main/class/Collection?scrollTo=hasAny) that I'm using it right, pass an array to the function.

I've already asked about this on stackoverflow but to no avail.

### Code sample

```typescript
//Permission Handler File
module.exports = {
    async getStaffPermissionFlags(guild, member){
        if(!member || !guild) return;
        const adminRoles = ['600912549570936833'];
        const moderatorRoles = ['659905403458682937'];

        return{
            admin: member.roles.cache.hasAny(adminRoles),
            moderator: member.roles.cache.hasAny(moderatorRoles)
        }
    },
    execute(client){
        client.permissionsHandler = {}
        client.permissionsHandler.getStaffPermissionFlags = this.getStaffPermissionFlags;
    }
}

//To access the handler from client
await interaction.client.permissionsHandler.getStaffPermissionFlags(interaction.guild, interaction.member);
```

### @discordjs/collection version

0.3.2

### Node.js version

16.7.0

### Operating system

Running on windows 10/Raspbian

### Priority this issue should have

Medium (should be fixed soon)

**Comment by ImRodry** [comment]
This method accepts spread parameters, meaning you need to do `hasAny(…arr)` in order to check all the elements in the array (arr being your array). The documentation can be a but confusing as it’s missing the spread operator so that could be fixed, but this seems intentional.

**Comment by OneAndonlyFinbar** [comment]
That seems to have fixed it, thanks diddnt know this. Updating the documentation might be good here.
